ms_loss_scaler_value: 1.0
ema: False
ms_amp_level: O2

optimizer:
  lr_init: 0.012
  start_factor: 1.0
  end_factor: 0.0
  warmup_epochs: 20
  gp_weight_decay: 0.0005
  momentum: 0.9
  loss_scale: 64
  group_param: yolov4

loss:
  name: YOLOv4Loss
  box: 10.  # box loss gain
  cls: 1.  # cls loss gain
  obj: 1.  # obj loss gain (scale with pixels)
  ignore_threshold: 0.7
  iou_threshold: 0.213
  label_smoothing: 0.0 # label smoothing epsilon

data:
  num_parallel_workers: 4

  train_transforms:
    - { func_name: mosaic, prob: 1.0, mosaic9_prob: 0.0, translate: 0.1, scale: 0.9 }
    - { func_name: mixup, prob: 0.1, alpha: 8.0, beta: 8.0, needed_mosaic: True }
    - { func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4 }
    - { func_name: label_norm, xyxy2xywh_: True }
    - { func_name: albumentations }
    - { func_name: fliplr, prob: 0.5 }
    - { func_name: label_pad, padding_size: 160, padding_value: -1 }
    - { func_name: image_norm, scale: 255. }
    - { func_name: image_transpose, bgr2rgb: True, hwc2chw: True }
    
  test_transforms:
    - { func_name: letterbox, scaleup: False }
    - { func_name: label_norm, xyxy2xywh_: True }
    - { func_name: label_pad, padding_size: 160, padding_value: -1 }
    - { func_name: image_norm, scale: 255. }
    - { func_name: image_transpose, bgr2rgb: True, hwc2chw: True }
